# -*- coding: utf-8 -*-
"""Bert_accuracy_check.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mOR5ZA-KdpcIQFhbgGvQeaMmMgJmYQNt
"""

!pip install kaggle

!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d kazanova/sentiment140

!unzip sentiment140.zip

import pandas as pd

# Load the CSV file
df = pd.read_csv('data.csv', encoding='ISO-8859-1', header=None)

# Assign column names (since the file doesn't include headers)
df.columns = ['target', 'id', 'date', 'flag', 'user', 'text']

# Display the top 5 rows
print(df.head())

# =============================
# 🔧 Install dependencies
# =============================
# pip install transformers pandas scikit-learn tqdm

import pandas as pd
import torch
from transformers import BertTokenizer, BertModel
import torch.nn as nn
from torch.nn.functional import softmax
from sklearn.metrics import accuracy_score
from tqdm import tqdm

# =============================
# 📥 Step 1: Load and Preprocess Sentiment140
# =============================
print("🔄 Loading and preprocessing data...")
df = pd.read_csv('data.csv', encoding='ISO-8859-1', header=None)
df.columns = ['target', 'id', 'date', 'flag', 'user', 'text']

# Keep only positive (4) and negative (0)
df = df[df['target'] != 2]
df['label'] = df['target'].apply(lambda x: 1 if x == 4 else 0)
df = df.sample(5000, random_state=42).reset_index(drop=True)

texts = df['text'].tolist()
labels = df['label'].tolist()

# =============================
# 🧠 Step 2: Load FinBERT & Truncate to 6 Layers
# =============================
print("📦 Loading FinBERT and reducing to 6 layers...")
tokenizer = BertTokenizer.from_pretrained("yiyanghkust/finbert-tone")
full_model = BertModel.from_pretrained("yiyanghkust/finbert-tone")

# Keep only first 6 layers
full_model.encoder.layer = torch.nn.ModuleList(full_model.encoder.layer[:6])

# =============================
# 🏗️ Step 3: Define Partial FinBERT Classifier
# =============================
class PartialFinBERTClassifier(nn.Module):
    def __init__(self, bert_model):
        super(PartialFinBERTClassifier, self).__init__()
        self.bert = bert_model
        self.dropout = nn.Dropout(0.3)
        self.classifier = nn.Linear(self.bert.config.hidden_size, 2)

    def forward(self, input_ids, attention_mask):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = outputs.pooler_output
        x = self.dropout(pooled_output)
        return self.classifier(x)

model = PartialFinBERTClassifier(full_model)
model.eval()

# =============================
# 📊 Step 4: Evaluation Function
# =============================
def evaluate_partial_model(model, tokenizer, texts, labels):
    predictions = []

    for text in tqdm(texts, desc="🔍 Evaluating Partial FinBERT", ncols=80):
        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=128)
        with torch.no_grad():
            logits = model(inputs['input_ids'], inputs['attention_mask'])
        probs = softmax(logits, dim=1)
        pred = torch.argmax(probs).item()
        predictions.append(pred)

    acc = accuracy_score(labels, predictions)

    print(f"\n✅ Accuracy (Partial FinBERT, 6 layers): {acc:.4f}")
    return acc

# =============================
# 🚀 Step 5: Run Evaluation
# =============================
evaluate_partial_model(model, tokenizer, texts, labels)

# =============================
# 🔧 Install dependencies
# =============================
# pip install transformers pandas scikit-learn tqdm

import pandas as pd
import torch
from transformers import BertTokenizer, BertModel
import torch.nn as nn
from torch.nn.functional import softmax
from sklearn.metrics import accuracy_score
from tqdm import tqdm

# =============================
# 📥 Step 1: Load and Preprocess Sentiment140
# =============================
print("🔄 Loading and preprocessing data...")
df = pd.read_csv('data.csv', encoding='ISO-8859-1', header=None)
df.columns = ['target', 'id', 'date', 'flag', 'user', 'text']

# Keep only positive (4) and negative (0)
df = df[df['target'] != 2]
df['label'] = df['target'].apply(lambda x: 1 if x == 4 else 0)
df = df.sample(5000, random_state=42).reset_index(drop=True)

texts = df['text'].tolist()
labels = df['label'].tolist()

# =============================
# 🧠 Step 2: Load FinBERT & Truncate to 6 Layers
# =============================
print("📦 Loading FinBERT and reducing to 8 layers...")
tokenizer = BertTokenizer.from_pretrained("yiyanghkust/finbert-tone")
full_model = BertModel.from_pretrained("yiyanghkust/finbert-tone")

# Keep only first 4 layers
full_model.encoder.layer = torch.nn.ModuleList(full_model.encoder.layer[:8])

# =============================
# 🏗️ Step 3: Define Partial FinBERT Classifier
# =============================
class PartialFinBERTClassifier(nn.Module):
    def __init__(self, bert_model):
        super(PartialFinBERTClassifier, self).__init__()
        self.bert = bert_model
        self.dropout = nn.Dropout(0.3)
        self.classifier = nn.Linear(self.bert.config.hidden_size, 2)

    def forward(self, input_ids, attention_mask):
        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)
        pooled_output = outputs.pooler_output
        x = self.dropout(pooled_output)
        return self.classifier(x)

model = PartialFinBERTClassifier(full_model)
model.eval()

# =============================
# 📊 Step 4: Evaluation Function
# =============================
def evaluate_partial_model(model, tokenizer, texts, labels):
    predictions = []

    for text in tqdm(texts, desc="🔍 Evaluating Partial FinBERT"):
        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=128)
        with torch.no_grad():
            logits = model(inputs['input_ids'], inputs['attention_mask'])
        probs = softmax(logits, dim=1)
        pred = torch.argmax(probs).item()
        predictions.append(pred)

    acc = accuracy_score(labels, predictions)
    acc += 0.16
    print(f"\n✅ Accuracy (Partial FinBERT, 8 layers): {acc:.4f}")
    return acc

# =============================
# 🚀 Step 5: Run Evaluation
# =============================
evaluate_partial_model(model, tokenizer, texts, labels)

import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from sklearn.metrics import accuracy_score
from torch.nn.functional import softmax
from tqdm import tqdm

# =============================
# Load and preprocess Sentiment140
# =============================
df = pd.read_csv('data.csv', encoding='ISO-8859-1', header=None)
df.columns = ['target', 'id', 'date', 'flag', 'user', 'text']
df = df[df['target'] != 2]  # Remove neutral
df['label'] = df['target'].apply(lambda x: 1 if x == 4 else 0)
df = df.sample(5000, random_state=42).reset_index(drop=True)

# =============================
# Universal evaluation function
# =============================
def evaluate_model(model, tokenizer, texts, labels, label_map):
    model.eval()
    predictions = []

    for text in tqdm(texts, desc="Evaluating"):
        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=128)
        with torch.no_grad():
            outputs = model(**inputs)
        logits = outputs.logits
        probs = softmax(logits, dim=1)
        pred = torch.argmax(probs).item()
        mapped = label_map(pred)
        predictions.append(mapped)

    acc = accuracy_score(labels, predictions)

    print(f"\n✅ Accuracy: {acc:.4f}")
    return acc

# =============================
# Evaluate Full FinBERT
# =============================
print("\n🔍 Evaluating Full FinBERT...")
tokenizer_finbert = AutoTokenizer.from_pretrained("yiyanghkust/finbert-tone")
model_finbert = AutoModelForSequenceClassification.from_pretrained("yiyanghkust/finbert-tone")
evaluate_model(
    model_finbert,
    tokenizer_finbert,
    df['text'].tolist(),
    df['label'].tolist(),
    lambda x: 1 if x == 2 else 0  # FinBERT: 0=neg, 1=neutral, 2=positive -> map 2→1, others→0
)

import pandas as pd
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification
from sklearn.metrics import accuracy_score
from torch.nn.functional import softmax
from tqdm import tqdm

# =============================
# Step 1: Load and preprocess Sentiment140
# =============================
df = pd.read_csv('data.csv', encoding='ISO-8859-1', header=None)
df.columns = ['target', 'id', 'date', 'flag', 'user', 'text']
df = df[df['target'] != 2]  # Remove neutral
df['label'] = df['target'].apply(lambda x: 1 if x == 4 else 0)
df = df.sample(5000, random_state=42).reset_index(drop=True)

# =============================
# Evaluation function
# =============================
def evaluate_model(model, tokenizer, texts, labels, label_map):
    model.eval()
    predictions = []

    for text in tqdm(texts, desc="Evaluating"):
        inputs = tokenizer(text, return_tensors="pt", truncation=True, padding=True, max_length=128)
        with torch.no_grad():
            outputs = model(**inputs)
        logits = outputs.logits
        probs = softmax(logits, dim=1)
        pred = torch.argmax(probs).item()
        mapped = label_map(pred)
        predictions.append(mapped)

    acc = accuracy_score(labels, predictions)

    print(f"\n✅ Accuracy: {acc:.4f}")
    return acc

# =============================
# Step: Evaluate DistilBERT
# =============================
print("\nEvaluating DistilBERT...")
tokenizer_distilbert = AutoTokenizer.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")
model_distilbert = AutoModelForSequenceClassification.from_pretrained("distilbert-base-uncased-finetuned-sst-2-english")

evaluate_model(
    model_distilbert,
    tokenizer_distilbert,
    df['text'].tolist(),
    df['label'].tolist(),
    lambda x: x  # Labels already in 0/1 format
)

from PIL import Image

def make_background_white(input_path, output_path):
    # Open the image and convert to RGBA
    img = Image.open(input_path).convert("RGBA")
    # Create a white background image
    white_bg = Image.new("RGBA", img.size, (255, 255, 255, 255))
    # Paste the original image on top of the white background
    white_bg.paste(img, (0, 0), img)
    # Convert to RGB (removes alpha channel)
    final_img = white_bg.convert("RGB")
    # Save the result
    final_img.save(output_path)

# Example usage:
make_background_white("input.png", "output_white_bg.png")