# -*- coding: utf-8 -*-
"""Copy of LSTM_Variants_with_Attention_Last.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ge4Us96U8IhSEyCqge8AmGsm1YrVNdrq
"""

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

torch.manual_seed(42)
np.random.seed(42)

SEQUENCE_LENGTH = 10
BATCH_SIZE = 64
EPOCHS = 100
LR = 0.001
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# ✅ Data Preprocessing
def prepare_data(df, sequence_length=SEQUENCE_LENGTH):
    df = df.drop(columns=['industry'], errors='ignore')
    df = df.select_dtypes(include=[np.number])  # Drop non-numeric cols like 'date'

    data = df.to_numpy().astype(np.float32)

    scaler_x = StandardScaler()
    scaler_y = StandardScaler()

    X = data[:, :-1]
    y = data[:, -1].reshape(-1, 1)

    X_scaled = scaler_x.fit_transform(X)
    y_scaled = scaler_y.fit_transform(y)

    X_seq, y_seq = [], []
    for i in range(len(X_scaled) - sequence_length):
        X_seq.append(X_scaled[i:i+sequence_length])
        y_seq.append(y_scaled[i+sequence_length])

    X_seq = np.array(X_seq)
    y_seq = np.array(y_seq)

    train_size = int(0.8 * len(X_seq))
    return (
        torch.tensor(X_seq[:train_size], dtype=torch.float32),
        torch.tensor(y_seq[:train_size], dtype=torch.float32),
        torch.tensor(X_seq[train_size:], dtype=torch.float32),
        torch.tensor(y_seq[train_size:], dtype=torch.float32),
        scaler_y
    )

# ✅ Attention Layer
class Attention(nn.Module):
    def __init__(self, hidden_dim):
        super().__init__()
        self.attn = nn.Linear(hidden_dim * 2, 1)  # BiLSTM has 2x hidden_dim

    def forward(self, lstm_output):
        weights = self.attn(lstm_output).squeeze(-1)
        attn_weights = torch.softmax(weights, dim=1).unsqueeze(-1)
        context = torch.sum(attn_weights * lstm_output, dim=1)
        return context

# ✅ BiLSTM + Attention Model
class BiLSTMWithAttention(nn.Module):
    def __init__(self, input_dim, hidden_dim):
        super().__init__()
        self.bilstm = nn.LSTM(input_dim, hidden_dim, batch_first=True, bidirectional=True)
        self.attention = Attention(hidden_dim)
        self.fc = nn.Linear(hidden_dim * 2, 1)

    def forward(self, x):
        bilstm_out, _ = self.bilstm(x)
        context = self.attention(bilstm_out)
        return self.fc(context)

# ✅ Training Function
def train_model(model, train_loader, criterion, optimizer):
    model.train()
    for epoch in range(EPOCHS):
        total_loss = 0
        for xb, yb in train_loader:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            pred = model(xb).squeeze()
            loss = criterion(pred, yb.squeeze())
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            total_loss += loss.item()
        if (epoch + 1) % 10 == 0:
            print(f"Epoch {epoch+1}/{EPOCHS}, Loss: {total_loss / len(train_loader):.4f}")

# ✅ Evaluation Function
def evaluate_model(model, X_test, y_test, scaler_y):
    model.eval()
    with torch.no_grad():
        preds = model(X_test.to(DEVICE)).cpu().numpy()
        true = y_test.cpu().numpy()
        preds = scaler_y.inverse_transform(preds)
        true = scaler_y.inverse_transform(true)

    mse = mean_squared_error(true, preds)
    mae = mean_absolute_error(true, preds)
    r2 = r2_score(true, preds)
    print(f"\n📊 BiLSTM + Attention Model Performance:\nMSE: {mse:.4f} | MAE: {mae:.4f} | R²: {r2:.4f}")
    return r2

# ✅ Run it all
df = pd.read_csv("final_with_industry.csv")
X_train, y_train, X_test, y_test, scaler_y = prepare_data(df)

train_ds = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)

input_dim = X_train.shape[2]
hidden_dim = 64

model = BiLSTMWithAttention(input_dim, hidden_dim).to(DEVICE)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=LR)

train_model(model, train_loader, criterion, optimizer)
evaluate_model(model, X_test, y_test, scaler_y)