# -*- coding: utf-8 -*-
"""Copy of LSTM_Variants_with_Attention_Last.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ge4Us96U8IhSEyCqge8AmGsm1YrVNdrq
"""

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import matplotlib.pyplot as plt
import seaborn as sns

# Set seeds
torch.manual_seed(42)
np.random.seed(42)

# Hyperparameters
SEQUENCE_LENGTH = 10
BATCH_SIZE = 64
EPOCHS = 100
LR = 0.001
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# Data Preparation
def prepare_data(df, sequence_length=SEQUENCE_LENGTH):
    df = df.drop(columns=['industry'], errors='ignore')  # Drop 'industry' if exists
    df = df.select_dtypes(include=[np.number])           # Keep only numeric

    data = df.to_numpy().astype(np.float32)
    scaler_x = StandardScaler()
    scaler_y = StandardScaler()

    X = data[:, :-1]
    y = data[:, -1].reshape(-1, 1)

    X_scaled = scaler_x.fit_transform(X)
    y_scaled = scaler_y.fit_transform(y)

    X_seq, y_seq = [], []
    for i in range(len(X_scaled) - sequence_length):
        X_seq.append(X_scaled[i:i+sequence_length])
        y_seq.append(y_scaled[i+sequence_length])

    X_seq = np.array(X_seq)
    y_seq = np.array(y_seq)

    train_size = int(0.8 * len(X_seq))
    X_train, y_train = X_seq[:train_size], y_seq[:train_size]
    X_test, y_test = X_seq[train_size:], y_seq[train_size:]

    return (torch.tensor(X_train, dtype=torch.float32),
            torch.tensor(y_train, dtype=torch.float32),
            torch.tensor(X_test, dtype=torch.float32),
            torch.tensor(y_test, dtype=torch.float32),
            scaler_y)

# BiGRU Model
class BiGRUModel(nn.Module):
    def __init__(self, input_dim, hidden_dim):
        super().__init__()
        self.bigrun = nn.GRU(input_dim, hidden_dim, batch_first=True, bidirectional=True)
        self.fc = nn.Linear(2 * hidden_dim, 1)

    def forward(self, x):
        gru_out, _ = self.bigrun(x)
        out = self.fc(gru_out[:, -1, :])
        return out

# Training Function
def train_model(model, train_loader, criterion, optimizer):
    model.train()
    losses = []
    for epoch in range(EPOCHS):
        epoch_loss = 0
        for xb, yb in train_loader:
            xb, yb = xb.to(DEVICE), yb.to(DEVICE)
            pred = model(xb).squeeze()
            loss = criterion(pred, yb.squeeze())
            optimizer.zero_grad()
            loss.backward()
            optimizer.step()
            epoch_loss += loss.item()
        avg_loss = epoch_loss / len(train_loader)
        losses.append(avg_loss)
        if (epoch+1) % 10 == 0:
            print(f"Epoch {epoch+1}/{EPOCHS}, Loss: {avg_loss:.4f}")
    return losses

# Evaluation Function
def evaluate_model(model, X_test, y_test, scaler_y):
    model.eval()
    with torch.no_grad():
        preds = model(X_test.to(DEVICE)).cpu().numpy()
        true = y_test.cpu().numpy()
        preds_rescaled = scaler_y.inverse_transform(preds)
        true_rescaled = scaler_y.inverse_transform(true)

    mse = mean_squared_error(true_rescaled, preds_rescaled)
    mae = mean_absolute_error(true_rescaled, preds_rescaled)
    r2 = r2_score(true_rescaled, preds_rescaled)

    print(f"\n📊 GRU Model Performance:\nMSE: {mse:.4f} | MAE: {mae:.4f} | R²: {r2:.4f}")
    return r2, preds_rescaled, true_rescaled

# Load data
df = pd.read_csv("final_with_industry.csv")
X_train, y_train, X_test, y_test, scaler_y = prepare_data(df)

# Build model
train_ds = TensorDataset(X_train, y_train)
train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True)

input_dim = X_train.shape[2]
hidden_dim = 64

model = BiGRUModel(input_dim, hidden_dim).to(DEVICE)
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr=LR)

# Train and evaluate
losses = train_model(model, train_loader, criterion, optimizer)
r2, preds_rescaled, true_rescaled = evaluate_model(model, X_test, y_test, scaler_y)

# Plot 1: Training Loss Curve
plt.figure(figsize=(8, 4))
plt.plot(losses, label="Training Loss", color='blue')
plt.title("Training Loss Over Epochs")
plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot 2: Predicted vs Actual Scatter (Improved)
plt.figure(figsize=(6, 6))
sns.scatterplot(x=true_rescaled.flatten(), y=preds_rescaled.flatten(), alpha=0.6, color="dodgerblue", label="Predictions")
plt.plot(
    [min(true_rescaled), max(true_rescaled)],
    [min(true_rescaled), max(true_rescaled)],
    'r--',
    label="Ideal Fit (y = x)"
)
plt.xlabel("Actual Target Values")
plt.ylabel("Predicted Target Values")
plt.title("Predicted vs Actual Values")
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()


# Plot 3: Residual Histogram
residuals = true_rescaled.flatten() - preds_rescaled.flatten()
plt.figure(figsize=(8, 4))
sns.histplot(residuals, bins=50, kde=True, color='purple')
plt.title("Residual Distribution")
plt.xlabel("Residual")
plt.ylabel("Frequency")
plt.grid(True)
plt.tight_layout()
plt.show()

# Plot 4: Actual vs Predicted Over Time (Enhanced Styling)
plt.figure(figsize=(12, 5))

# Use smooth line colors with some transparency
plt.plot(true_rescaled.flatten(), label="Actual", color='#1f77b4', linewidth=2)  # Blue
plt.plot(preds_rescaled.flatten(), label="Predicted", color='#ff7f0e', linewidth=2, alpha=0.8)  # Orange

plt.title("Actual vs Predicted Over Time", fontsize=14)
plt.xlabel("Time Step", fontsize=12)
plt.ylabel("Target Variable", fontsize=12)

plt.legend(frameon=True, loc="best")
plt.grid(True, linestyle='--', alpha=0.4)
plt.tight_layout()
plt.show()