# -*- coding: utf-8 -*-
"""Copy of LSTM_Variants_with_Attention_Last.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ge4Us96U8IhSEyCqge8AmGsm1YrVNdrq
"""

results_df = pd.read_csv("industry_results.csv")

# R² Bar Plot
plt.figure(figsize=(10, 6))
sns.barplot(data=results_df, x="R2", y="Industry", palette="magma")
plt.title("R² Score by Industry")
plt.tight_layout()
plt.show()

plt.figure(figsize=(6,5))
sns.heatmap(results_df[["R2", "MSE", "MAE", "Weight", "Bias"]].corr(), annot=True, cmap="vlag", fmt=".2f")
plt.title("📈 Correlation Matrix")
plt.tight_layout()
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Simulated values (replace these with actual test predictions and truths)
np.random.seed(42)
actuals = np.linspace(14, 23, 90)
preds = actuals + np.random.normal(0, 0.5, size=len(actuals))  # slightly noisy prediction

# Plot similar to your screenshot
plt.figure(figsize=(14, 6))
plt.scatter(range(len(preds)), preds, color='red', label="Predicted Close", s=20)
plt.scatter(range(len(actuals)), actuals, color='green', label="Actual Close", s=20)
plt.xlabel("Time")
plt.ylabel("Closing Price")
plt.title("Predicted vs Actual Close", fontsize=13, fontweight='bold')
plt.legend()
plt.grid(True)
plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Load the data
df = pd.read_csv("industry_results.csv")

# Select metrics for radar chart
metrics = ['R2', 'MSE', 'MAE', 'Weight', 'Bias']
industries = df['Industry']
num_vars = len(metrics)

# Normalize the data for better comparison
normalized_df = df.copy()
for metric in metrics:
    min_val = df[metric].min()
    max_val = df[metric].max()
    normalized_df[metric] = (df[metric] - min_val) / (max_val - min_val)

# Prepare angles for radar chart
angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
angles += angles[:1]  # Repeat the first value to close the circle

# Create radar chart
fig, ax = plt.subplots(figsize=(12, 12), subplot_kw=dict(polar=True))

for i, row in normalized_df.iterrows():
    values = row[metrics].tolist()
    values += values[:1]
    ax.plot(angles, values, label=row['Industry'])
    ax.fill(angles, values, alpha=0.1)

# Format the radar chart
ax.set_theta_offset(np.pi / 2)
ax.set_theta_direction(-1)
ax.set_thetagrids(np.degrees(angles[:-1]), metrics)

# Add title with extra padding
ax.set_title("Radar Chart of Industry Metrics", size=18, pad=40)

# Add legend with extra gap
ax.legend(loc='upper right', bbox_to_anchor=(1.4, 1.15), fontsize='small')

# Save the chart as PNG
plt.tight_layout()
plt.savefig("industry_radar_chart.png", dpi=300)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Load the data
df = pd.read_csv("industry_results.csv")

# Metrics for radar chart
metrics = ['R2', 'MSE', 'MAE', 'Weight', 'Bias']
num_vars = len(metrics)

# Normalize the data for better comparison
normalized_df = df.copy()
for metric in metrics:
    min_val = df[metric].min()
    max_val = df[metric].max()
    normalized_df[metric] = (df[metric] - min_val) / (max_val - min_val)

# Prepare angles for radar chart
angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
angles += angles[:1]  # Complete the circle

# Define groups based on R² score
groups = {
    "High (0.9-1.0)": normalized_df[(df['R2'] >= 0.9) & (df['R2'] <= 1.0)],
    "Medium (0.75-0.9)": normalized_df[(df['R2'] >= 0.75) & (df['R2'] < 0.9)],
    "Low (0.6-0.75)": normalized_df[(df['R2'] >= 0.6) & (df['R2'] < 0.75)],
}

# Use a set of very different colors
color_list = [
    'red', 'green', 'blue', 'orange', 'purple',
    'brown', 'pink', 'gray', 'olive', 'cyan',
    'magenta', 'gold', 'teal', 'navy', 'lime'
]

# Create radar charts for each group
for group_name, group_data in groups.items():
    fig, ax = plt.subplots(figsize=(10, 10), subplot_kw=dict(polar=True))

    for idx, (i, row) in enumerate(group_data.iterrows()):
        values = row[metrics].tolist()
        values += values[:1]  # Complete the circle
        color = color_list[idx % len(color_list)]  # Cycle through colors if needed
        ax.plot(angles, values, label=row['Industry'], color=color, linewidth=2)
        ax.fill(angles, values, alpha=0.1, color=color)

    # Format the radar chart
    ax.set_theta_offset(np.pi / 2)
    ax.set_theta_direction(-1)
    ax.set_thetagrids(np.degrees(angles[:-1]), metrics)

    # Title only for group
    ax.set_title(f"Radar Chart: {group_name}", size=18, pad=40)

    # Legend for industries
    ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1), fontsize='small')
    plt.tight_layout()

    # Save each chart separately
    filename = group_name.replace(" ", "_").replace("(", "").replace(")", "").replace("-", "_to_")
    plt.savefig(f"industry_radar_chart_{filename}.png", dpi=300)
    plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# Load the data
df = pd.read_csv("industry_results.csv")

# Metrics for radar chart
metrics = ['R2', 'MSE', 'MAE', 'Weight', 'Bias']
num_vars = len(metrics)

# Normalize the data for better comparison
normalized_df = df.copy()
for metric in metrics:
    min_val = df[metric].min()
    max_val = df[metric].max()
    normalized_df[metric] = (df[metric] - min_val) / (max_val - min_val)

# Prepare angles for radar chart
angles = np.linspace(0, 2 * np.pi, num_vars, endpoint=False).tolist()
angles += angles[:1]  # Complete the circle

# Define groups based on R² score
groups = {
    "High (0.9-1.0)": normalized_df[(df['R2'] >= 0.9) & (df['R2'] <= 1.0)],
    "Medium (0.75-0.9)": normalized_df[(df['R2'] >= 0.75) & (df['R2'] < 0.9)],
    "Low (0.6-0.75)": normalized_df[(df['R2'] >= 0.6) & (df['R2'] < 0.75)],
}

# Use a set of very different colors
color_list = [
    'red', 'green', 'blue', 'orange', 'purple',
    'brown', 'pink', 'gray', 'olive', 'cyan',
    'magenta', 'gold', 'teal', 'navy', 'lime'
]

# Create radar charts for each group
for group_name, group_data in groups.items():
    fig, ax = plt.subplots(figsize=(6, 6), subplot_kw=dict(polar=True))  # Smaller figure size

    for idx, (i, row) in enumerate(group_data.iterrows()):
        values = row[metrics].tolist()
        values += values[:1]  # Complete the circle
        color = color_list[idx % len(color_list)]  # Cycle through colors if needed
        ax.plot(angles, values, label=row['Industry'], color=color, linewidth=2)
        ax.fill(angles, values, alpha=0.1, color=color)

    # Format the radar chart
    ax.set_theta_offset(np.pi / 2)
    ax.set_theta_direction(-1)
    ax.set_thetagrids(np.degrees(angles[:-1]), metrics)

    # Make the circle tighter
    ax.set_rlabel_position(0)
    ax.set_ylim(0, 1)  # Keep the scale from 0 to 1
    ax.set_frame_on(True)

    # Title only for group
    ax.set_title(f"Radar Chart: {group_name}", size=16, pad=20)

    # Legend placed even farther away
    ax.legend(
        loc='upper right',
        bbox_to_anchor=(1.7, 1.2),
        fontsize='small',
        frameon=False  # Optional: remove box around legend
    )

    plt.tight_layout()

    # Save each chart separately
    filename = group_name.replace(" ", "_").replace("(", "").replace(")", "").replace("-", "_to_")
    plt.savefig(f"1_industry_radar_chart_{filename}.png", dpi=300)
    plt.show()

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Load your data
df = pd.read_csv("industry_results.csv")

# Set dark background style
# plt.style.use('dark_background')

# Create the figure
plt.figure(figsize=(12, 8))

# Plot bubble chart
bubble_plot = sns.scatterplot(
    data=df,
    x='R2',
    y='MSE',
    size='MAE',
    hue='Industry',
    palette='husl',
    sizes=(100, 2000),
    alpha=0.7,
    edgecolor='black'
)

# Customize labels and grid
plt.title('Bubble Chart of Industry Metrics', fontsize=16, pad=20, color='white')
plt.xlabel('R² Score', color='white')
plt.ylabel('Mean Squared Error (MSE)', color='white')
plt.grid(True, linestyle='--', linewidth=0.5, color='gray')
bubble_plot.set_facecolor('#1c1c1c')
bubble_plot.tick_params(colors='white')

# Legend formatting
plt.legend(loc='upper left', bbox_to_anchor=(1.02, 1), borderaxespad=0, title='Industry')

# Save to file
plt.tight_layout()
plt.savefig("industry_bubble_chart_dark_with_legend.png", dpi=300, facecolor='black')
plt.show()

import matplotlib.pyplot as plt

# Data
models = [
    "Full FinBERT",
    "FinBERT (4 layers)",
    "FinBERT (6 layers)",
    "FinBERT (8 layers)",
    "DistilBERT (6 layers)"
]
accuracies = [0.7042, 0.6592, 0.6606, 0.6582, 0.8146]

# Plot
plt.figure(figsize=(10, 6))
bars = plt.bar(models, accuracies, color=['gray', 'skyblue', 'skyblue', 'skyblue', 'lightgreen'])

# Highlight best performer
bars[-1].set_color('green')

# Annotate bars
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2.0, yval + 0.01, f"{yval:.4f}", ha='center', va='bottom')

# Aesthetics
plt.title("Model Accuracy Comparison")
plt.xlabel("Models")
plt.ylabel("Accuracy")
plt.ylim(0.4, 0.75)
plt.xticks(rotation=20)
plt.grid(axis='y', linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Load the dataset
df_results = pd.read_csv("New_Data_Set.csv")

# Drop missing values in required columns
df_results.dropna(subset=["Industry", "rsquared", "ticker"], inplace=True)

# Aggregate data to get count of tickers per industry
ticker_counts = df_results.groupby("Industry")["ticker"].count()

df_results["Ticker Count"] = df_results["Industry"].map(ticker_counts)

# Create a bubble chart similar to the sample visualization
plt.figure(figsize=(14, 8))
sns.scatterplot(
    x=df_results["Industry"],
    y=df_results["rsquared"],
    size=df_results["Ticker Count"],
    sizes=(50, 1000),
    hue=df_results["Industry"],
    alpha=0.7,
    edgecolor="black",
    palette="Set2"
)
plt.xticks(rotation=45, ha='right')
plt.xlabel("Industry", fontsize=12)
plt.ylabel("R-squared Value", fontsize=12)
plt.title("Industry vs. R-squared Bubble Chart", fontsize=14)
plt.legend(title="Industry", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, linestyle='--', alpha=0.5)
plt.show()

